### ISSUE TITLE
Plex shows "Device not found" even when connected

### ISSUE THREAD

**Issue by mikerohan** [tellytv/telly#119]
Hi,

PLEX configuration is showing this message: 

> Device not found. Ensure your device is powered on and connected to your network.

But the connection is OK. I'm even recording a channel...

**Comment by hairychris** [comment]
What version are you running? Check the release notes for 0.6 it mentions this https://github.com/tombowditch/telly/releases/tag/v0.6

**Comment by HazCod** [comment]
Try restarting Plex.

**Comment by mikerohan** [comment]
Great! Restarting Plex did the trick

**Comment by abraovic** [comment]
Hi,

I'm having the same issue. I've tried restarting Plex server, and even whole machine but nothing seems to work. When I'm adding this to Plex it shows me a list of available channels. When I try to open `http://localhost:6077/lineup.json` I do get list of available streams. Those streams works with VLC player. 

[Screenshot](https://imgur.com/a/OsT6UII) 

Everything is running on Ubuntu 16.04 LTS so I've downloaded this [release](https://github.com/tellytv/telly/releases/download/v1.1.0-Beta5/telly-1.1.0.5.linux-386.tar.gz).

```
System:
Ubuntu 16.04 LTS
Plex Server 1.14.1.54.88
```

**Comment by chazlarson** [comment]
Is there an issue aside from the config saying "Device not found?"  You're able to add the DVR, but do streams play?

**Comment by chazlarson** [comment]
You can or cannot see channels in Plex?  You mention that the lineup.json shows channels, and "Plex ... shows me a list of available channels".

Or does "can not even see the streams in Plex" mean you can see them in the guide but can't tune any channels?  This is often a network issue.

I'd like to see the config file you're using, the output from telly when it runs, and the result of using `curl` to retrieve one of those channel URLS from `lineup.json` _from the machine running plex_.

Consider bringing this over to the telly discord; might make for easier interaction and more eyes will see it.

**Comment by abraovic** [comment]
Hi @chazlarson 

[Here are screenshots](https://imgur.com/a/30w4ZCv) of what I have on my Plex server while and when I add this to the Plex.

Here is what I use for telly. No additional config is used.
```
./telly --iptv.playlist=/home/passuser/Downloads/tv_channels_MA020.m3u

Flag --iptv.playlist has been deprecated, use the configuration file instead.
INFO[2019-01-23T09:17:04+01:00] telly is preparing to go live (version=1.1.0.5, branch=dev, revision=567f9062e94f32fd46bd6b82f10c1ac2e7f711c5) 
WARN[2019-01-23T09:17:04+01:00] Legacy --iptv.playlist argument or environment variable provided, using Custom provider with default configuration, this may fail! If so, you should use a configuration file for full flexibility. 
INFO[2019-01-23T09:17:04+01:00] Loading M3U from /home/passuser/Downloads/tv_channels_MA020.m3u 
INFO[2019-01-23T09:17:04+01:00] Loaded 6 channels into the lineup from Legacy provider created using arguments/environment variables 
INFO[2019-01-23T09:17:04+01:00] telly is live and on the air!                
INFO[2019-01-23T09:17:04+01:00] Broadcasting from http://localhost:6077/     
INFO[2019-01-23T09:17:04+01:00] EPG URL: http://localhost:6077/epg.xml       
INFO[2019-01-23T09:21:36+01:00] Serving channel number 10000                 
INFO[2019-01-23T09:21:50+01:00] Serving channel number 10000                 
INFO[2019-01-23T09:22:14+01:00] Serving channel number 10000                 
INFO[2019-01-23T09:22:33+01:00] Serving channel number 10000 
```

Channel number 10000 with url `http://localhost:6077/auto/v10000` is playing in VLC player.

And here is a requested curl:

```
curl localhost:6077/lineup.json

[{"GuideName":"A\u0026E HD","GuideNumber":"10000","HD":1,"URL":"http://localhost:6077/auto/v10000"},{"GuideName":"A\u0026E SD","GuideNumber":"10001","URL":"http://localhost:6077/auto/v10001"},{"GuideName":"AMC HD","GuideNumber":"10002","HD":1,"URL":"http://localhost:6077/auto/v10002"},{"GuideName":"AMC SD","GuideNumber":"10003","URL":"http://localhost:6077/auto/v10003"},{"GuideName":"AXN HD","GuideNumber":"10004","HD":1,"URL":"http://localhost:6077/auto/v10004"},{"GuideName":"AXN SD","GuideNumber":"10005","URL":"http://localhost:6077/auto/v10005"}]
```

[Here is m3u file](https://ufile.io/y73oa) that is being used.

**Comment by chazlarson** [comment]
Several things to sort.

First, you're using 1.1, but configuring it like 1.0.  Please take a look at this walkthrough and configure it as described there.

https://github.com/tellytv/telly/wiki/Standalone-Walkthrough%3A-Linux-with-config-file

I assume you're only configuring one of those channels with guide data, since Plex wouldn't allow you to save the DVFR and get to the grid with duplicate channels.

Which guide data are you using?  Does your provider offer any guide of their own?

Is VLC player running on the same machine that is running Plex?

The `curl` command I'm looking for is one that attempted to load the channel itself, not the list of channels.  Run this from the machine which is running Plex.

`curl -f -L -v -o output.dat http://localhost:6077/auto/v10000`

There's an article about why we should run that here:

https://github.com/tellytv/telly/wiki/FAQ

**Comment by abraovic** [comment]
Hi @chazlarson 

thanks for your response. Sry for a late replay. This is a side project for me so I'm struggling to get some time to do this.

It seems there can be something related to authentication. I'm able to watch a few seconds of tv on plex but after that it freezes and then I get:
> Recording failed. Please check your tuner or antenna

When I curl channel from list it closes connection faster than I get the chance to press `Crtl*C`. [Here is output file](https://ufile.io/01acu). And [here is terminal output](https://pastebin.com/7kS7QXyi).

[Here](https://ufile.io/fmne3) is a requested curl command output for one channel from the `lineup.json`.

I was testing it with a [different m3u](https://ufile.io/aqdre) list now.

As for config. When I use config file as described I get 0 channels into lineup, and when I use that flag that I was using before then I get 6 channels into lineup. Maybe I did something wrong. You can check it [here](https://ufile.io/9c1o2). As for EPG I let Plex to select it for me since I do not have any.

**Comment by chazlarson** [comment]
No worries; it's a side project for all.

First, the config file approach is showing no channels because the filter is filtering them all out.  This is happening because the m3u files you are using are plain m3u, not m3u_plus, which telly is expecting.  The filter is including only channels that have any of a list of words in the `group-title` tag.  Your m3u file contains no `group-title` tags, therefore nothing matches the filter, therefore, telly publishes 0 channels.

Both these things are described in detail in the wiki.

[IPTV requirements](https://github.com/tellytv/telly/wiki/Prerequisites%3A-IPTV-Account)
[Filtering](https://github.com/tellytv/telly/wiki/Running-Telly%3A-Filtering)
[Running under linux with a config file](https://github.com/tellytv/telly/wiki/Standalone-Walkthrough%3A-Linux-with-config-file)

Using plain M3U files will cause problems with filtering and possibly EPG matching.

The new M3U has the same problem; it's also a plain m3u, not m3u_plus.

The pastebin output seems to demonstrate that retrieving a link outside telly's involvement results in the server sending ten seconds of video and then closing the connection.  There isn't anything telly can do about that.  When you go through telly, telly will just issue a redirect to that same URL, so the same thing happens.

**Comment by abraovic** [comment]
Hi @chazlarson,

I've managed to access channels and record them. It is still saying "Device not found" but everything seems to work. So, as far as I concern it is not an issue any more.

Thanks for all your help.

**Comment by nweishar** [comment]
Opening port 1900udp did it for me
