### ISSUE TITLE
Getting 0 channels out of a simple M3U file 

### ISSUE THREAD

**Issue by fabakhti** [tellytv/telly#147]
I can't seem to get telly to read channels out of my M3U file. I've got it down to the simple one below and still fails to find channels. No error messages and nothing in debug logging. Before I start debugging I thought I would ask in case I'm missing something obvious. 

>
> #EXTM3U
> #EXTINF:-1, Sports 2 
> http://domain.com:8080/live/id/id/1287.ts
>

**Comment by chazlarson** [comment]
You most likely need to add the `--filter.regex-inclusive` flag.  The default regex behavior now is to exclude everything.

Some examples:

I'm starting with an Iris M3U.  It contains around 8000 channels:
```
| => curl "http://REDACTED" | egrep -i -e "tvg-id" | wc -l
    8010
```
I've downloaded the m3u to iptv.m3u.
Let's start telly with no parameters:
```
| => ./telly
INFO[0000] Starting telly (version=1.0.3, branch=master, revision=e543e7080a57eb6d7b6dd4b0ad27b789d3aa6c08)
INFO[0000] Build context (go=go1.10.3, user=root@21d9dfe90d82, date=20180811-23:23:07)
WARN[0000] using default m3u option, 'iptv.m3u'. launch telly with the --iptv.playlist=yourfile.m3u option to change this!
INFO[0000] found 0 channels
```

no channels found, because the default behavior is "exclude everything"

Flip the default:
```
| => ./telly --filter.regex-inclusive
INFO[0000] Starting telly (version=1.0.3, branch=master, revision=e543e7080a57eb6d7b6dd4b0ad27b789d3aa6c08)
INFO[0000] Build context (go=go1.10.3, user=root@21d9dfe90d82, date=20180811-23:23:07)
WARN[0000] using default m3u option, 'iptv.m3u'. launch telly with the --iptv.playlist=yourfile.m3u option to change this!
INFO[0000] found 8010 channels
```

[4:07 PM] chazlarson: There are 61 channels that contain "ESPN" in this m3u.  Let's add that to the filter:
```
| => ./telly --filter.regex="ESPN"
INFO[0000] Starting telly (version=1.0.3, branch=master, revision=e543e7080a57eb6d7b6dd4b0ad27b789d3aa6c08)
INFO[0000] Build context (go=go1.10.3, user=root@21d9dfe90d82, date=20180811-23:23:07)
WARN[0000] using default m3u option, 'iptv.m3u'. launch telly with the --iptv.playlist=yourfile.m3u option to change this!
INFO[0000] found 7949 channels
```

Since the default is to blacklist, those 61 channels were removed.

flip the inclusive flag, and we get only those 61:
```
| => ./telly --filter.regex="ESPN" --filter.regex-inclusive
INFO[0000] Starting telly (version=1.0.3, branch=master, revision=e543e7080a57eb6d7b6dd4b0ad27b789d3aa6c08)
INFO[0000] Build context (go=go1.10.3, user=root@21d9dfe90d82, date=20180811-23:23:07)
WARN[0000] using default m3u option, 'iptv.m3u'. launch telly with the --iptv.playlist=yourfile.m3u option to change this!
INFO[0000] found 61 channels
```

**Comment by fabakhti** [comment]
That was it! Thanks for the help.
